### ISSUE TITLE
Admin todo

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/essential_skills_RRC#20]
* [x] move `copa_america` goal text file somewhere besides the root of the repo
* [ ] ~delete `resources` folder that's at root~
* [x] use `resources` folder to host `copa_america` goals and other script
* [x] find a place for the uber data set to be hosted, so students can download it
* [x] complete `wget` instructions in git.md#L38

**Comment by gforsyth** [comment]
All done.
