### ISSUE TITLE
Admin TODO list

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/essential_skills_RRC#3]
- [x] Figure out if we're in a lab or people are bringing laptops (lab)
  - [ ] What copy/paste commands are available (Is it Ctrl+Shift+V or Shift-Insert?)
- [ ] Instructions for signing up for GitHub w/education pack
- [ ] Figure out if we will have a screen/ projector to show what we are doing so students can follow us.

**Comment by ncclementi** [comment]
Things we need to request to be installed
(Probably I'm missing something, feel free to edit the comment)
- [ ] Nano
- [ ] Git
- [ ] Python 3.*
- [ ] Ipython
- [ ] Numpy
- [ ] Scipy
- [ ] Simpy
- [ ] Jupyter notebooks 
- [ ] Numba
- [ ] matplotlib

**Comment by gforsyth** [comment]
I think these things are all settled, I'm going to close this out.
